### ISSUE TITLE
TRT-LLM image

### ISSUE THREAD

**Issue by YunchaoYang** [leimao/TensorRT-Docker-Image#2]
Hello @leimao,

Thanks for sharing great TRT Docker image build script. Just wondering if this will work for TRT-LLM?
What steps does it require to build a TRT-LLM image?

Thanks a lot!

**Comment by leimao** [comment]
I have little experience in using TRT-LLM.
As far as I know TRT-LLM is built on TRT so you would require installing additional dependencies. They have also provided [Dockerfiles](https://github.com/NVIDIA/TensorRT-LLM/tree/main/docker) for building containers, so you should use theirs instead.
